export const booksData = [
  {
    slug: "oxford-3000",
    name: "Oxford 3000 Vocabulary",
    image: "https://example.com/oxford-3000.jpg",
    link: "https://oxfordlearnersdictionaries.com/wordlists/oxford3000",
  },
  {
    slug: "oxford-idioms",
    name: "Oxford Idioms Advanced",
    image: "https://example.com/oxford-idioms.jpg",
    link: "https://oxfordlearnersdictionaries.com/idioms",
  },
  {
    slug: "cambridge-phrasal-verbs",
    name: "Cambridge Phrasal Verbs",
    image: "https://example.com/cambridge-phrasal.jpg",
    link: "https://dictionary.cambridge.org/grammar/phrasal-verbs",
  },
  {
    slug: "collins-cobuild",
    name: "Collins COBUILD Idioms",
    image: "https://example.com/collins-cobuild.jpg",
    link: "https://collinsdictionary.com/idioms",
  },
  {
    slug: "english-for-business",
    name: "English for Business",
    image: "https://example.com/business-english.jpg",
    link: "https://example.com/business-english",
  },
  {
    slug: "toefl-vocabulary",
    name: "TOEFL Vocabulary",
    image: "https://example.com/toefl-vocab.jpg",
    link: "https://example.com/toefl-vocabulary",
  },
  {
    slug: "ielts-academic",
    name: "IELTS Academic Vocabulary",
    image: "https://example.com/ielts-academic.jpg",
    link: "https://example.com/ielts-vocabulary",
  },
  {
    slug: "everyday-english",
    name: "Everyday English Phrases",
    image: "https://example.com/everyday-english.jpg",
    link: "https://example.com/everyday-english",
  },
  {
    slug: "slang-english",
    name: "English Slang and Colloquialisms",
    image: "https://example.com/slang-english.jpg",
    link: "https://example.com/slang-english",
  },
  {
    slug: "academic-word-list",
    name: "Academic Word List",
    image: "https://example.com/academic-word-list.jpg",
    link: "https://example.com/academic-word-list",
  },
];

export const wordsData = [
  {
    bookSlug: "oxford-idioms-and-phrasal-verbs-advanced",
    slug: "oxford-idioms-and-phrasal-verbs-advanced_burn_the_midnight_oil",
    word: "burn the midnight oil",
    usPronounce: "/bɝːn ðə ˈmɪd.naɪt ɔɪl/",
    ukPronounce: "/bɜːn ðə ˈmɪd.naɪt ɔɪl/",
    translation: "làm việc khuya",
    remember: "Work late.",
  },
  {
    bookSlug: "oxford-idioms-and-phrasal-verbs-advanced",
    slug: "oxford-idioms-and-phrasal-verbs-advanced_throw_in_the_towel",
    word: "throw in the towel",
    usPronounce: "/θroʊ ɪn ðə ˈtaʊəl/",
    ukPronounce: "/θrəʊ ɪn ðə ˈtaʊəl/",
    translation: "bỏ cuộc",
    remember: "",
  },
  {
    bookSlug: "oxford-idioms-and-phrasal-verbs-advanced",
    slug: "oxford-idioms-and-phrasal-verbs-advanced_get_off_on_the_wrong_foot",
    word: "get off on the wrong foot",
    usPronounce: "/ɡet ɔːf ɑːn ðə rɔːŋ fʊt/",
    ukPronounce: "/ɡet ɒf ɒn ðə rɒŋ fʊt/",
    translation: "bắt đầu sai lầm",
    remember: "Bad start.",
  },
  {
    bookSlug: "oxford-idioms-and-phrasal-verbs-advanced",
    slug: "oxford-idioms-and-phrasal-verbs-advanced_take_something_with_a_pinch_of_salt",
    word: "take something with a pinch of salt",
    usPronounce: "/teɪk ˈsʌm.θɪŋ wɪð ə pɪntʃ əv sɔːlt/",
    ukPronounce: "/teɪk ˈsʌm.θɪŋ wɪð ə pɪntʃ əv sɒlt/",
    translation: "nghi ngờ điều gì đó",
    remember: "",
  },
  {
    bookSlug: "oxford-idioms-and-phrasal-verbs-advanced",
    slug: "oxford-idioms-and-phrasal-verbs-advanced_spill_the_beans",
    word: "spill the beans",
    usPronounce: "/spɪl ðə biːnz/",
    ukPronounce: "/spɪl ðə biːnz/",
    translation: "tiết lộ bí mật",
    remember: "Tell secrets.",
  },
  {
    bookSlug: "oxford-idioms-and-phrasal-verbs-advanced",
    slug: "oxford-idioms-and-phrasal-verbs-advanced_bite_the_bullet",
    word: "bite the bullet",
    usPronounce: "/baɪt ðə ˈbʊl.ɪt/",
    ukPronounce: "/baɪt ðə ˈbʊl.ɪt/",
    translation: "chấp nhận khó khăn",
    remember: "",
  },
  {
    bookSlug: "oxford-idioms-and-phrasal-verbs-advanced",
    slug: "oxford-idioms-and-phrasal-verbs-advanced_go_the_extra_mile",
    word: "go the extra mile",
    usPronounce: "/ɡoʊ ði ˈek.strə maɪl/",
    ukPronounce: "/ɡəʊ ði ˈek.strə maɪl/",
    translation: "nỗ lực thêm",
    remember: "Do more.",
  },
  {
    bookSlug: "oxford-idioms-and-phrasal-verbs-advanced",
    slug: "oxford-idioms-and-phrasal-verbs-advanced_hit_the_nail_on_the_head",
    word: "hit the nail on the head",
    usPronounce: "/hɪt ðə neɪl ɑːn ðə hed/",
    ukPronounce: "/hɪt ðə neɪl ɒn ðə hed/",
    translation: "nói đúng trọng tâm",
    remember: "",
  },
  {
    bookSlug: "oxford-idioms-and-phrasal-verbs-advanced",
    slug: "oxford-idioms-and-phrasal-verbs-advanced_kick_the_bucket",
    word: "kick the bucket",
    usPronounce: "/kɪk ðə ˈbʌk.ɪt/",
    ukPronounce: "/kɪk ðə ˈbʌk.ɪt/",
    translation: "chết",
    remember: "Pass away.",
  },
  {
    bookSlug: "oxford-idioms-and-phrasal-verbs-advanced",
    slug: "oxford-idioms-and-phrasal-verbs-advanced_let_the_cat_out_of_the_bag",
    word: "let the cat out of the bag",
    usPronounce: "/let ðə kæt aʊt əv ðə bæɡ/",
    ukPronounce: "/let ðə kæt aʊt əv ðə bæɡ/",
    translation: "lộ bí mật",
    remember: "",
  },
  {
    bookSlug: "oxford-idioms-and-phrasal-verbs-advanced",
    slug: "oxford-idioms-and-phrasal-verbs-advanced_turn_a_blind_eye",
    word: "turn a blind eye",
    usPronounce: "/tɝːn ə blaɪnd aɪ/",
    ukPronounce: "/tɜːn ə blaɪnd aɪ/",
    translation: "làm ngơ",
    remember: "Ignore it.",
  },
  {
    bookSlug: "oxford-idioms-and-phrasal-verbs-advanced",
    slug: "oxford-idioms-and-phrasal-verbs-advanced_bark_is_worse_than_bite",
    word: "bark is worse than bite",
    usPronounce: "/bɑːrk ɪz wɝːs ðæn baɪt/",
    ukPronounce: "/bɑːk ɪz wɜːs ðæn baɪt/",
    translation: "nói dữ nhưng hiền",
    remember: "",
  },
  {
    bookSlug: "oxford-idioms-and-phrasal-verbs-advanced",
    slug: "oxford-idioms-and-phrasal-verbs-advanced_break_the_ice",
    word: "break the ice",
    usPronounce: "/breɪk ði aɪs/",
    ukPronounce: "/breɪk ði aɪs/",
    translation: "phá băng",
    remember: "Start talking.",
  },
  {
    bookSlug: "oxford-idioms-and-phrasal-verbs-advanced",
    slug: "oxford-idioms-and-phrasal-verbs-advanced_cost_an_arm_and_a_leg",
    word: "cost an arm and a leg",
    usPronounce: "/kɔːst ən ɑːrm ənd ə leɡ/",
    ukPronounce: "/kɒst ən ɑːm ənd ə leɡ/",
    translation: "rất đắt",
    remember: "",
  },
  {
    bookSlug: "oxford-idioms-and-phrasal-verbs-advanced",
    slug: "oxford-idioms-and-phrasal-verbs-advanced_get_cold_feet",
    word: "get cold feet",
    usPronounce: "/ɡet koʊld fiːt/",
    ukPronounce: "/ɡet kəʊld fiːt/",
    translation: "sợ hãi, chùn bước",
    remember: "Feel nervous.",
  },
  {
    bookSlug: "oxford-idioms-and-phrasal-verbs-advanced",
    slug: "oxford-idioms-and-phrasal-verbs-advanced_pull_someones_leg",
    word: "pull someone's leg",
    usPronounce: "/pʊl ˈsʌm.wʌnz leɡ/",
    ukPronounce: "/pʊl ˈsʌm.wʌnz leɡ/",
    translation: "trêu đùa ai",
    remember: "",
  },
  {
    bookSlug: "oxford-idioms-and-phrasal-verbs-advanced",
    slug: "oxford-idioms-and-phrasal-verbs-advanced_sit_on_the_fence",
    word: "sit on the fence",
    usPronounce: "/sɪt ɑːn ðə fens/",
    ukPronounce: "/sɪt ɒn ðə fens/",
    translation: "do dự, không quyết định",
    remember: "Stay neutral.",
  },
  {
    bookSlug: "oxford-idioms-and-phrasal-verbs-advanced",
    slug: "oxford-idioms-and-phrasal-verbs-advanced_under_the_weather",
    word: "under the weather",
    usPronounce: "/ˈʌn.dɚ ðə ˈweð.ɚ/",
    ukPronounce: "/ˈʌn.də ðə ˈweð.ə/",
    translation: "ốm yếu",
    remember: "",
  },
  {
    bookSlug: "oxford-idioms-and-phrasal-verbs-advanced",
    slug: "oxford-idioms-and-phrasal-verbs-advanced_add_fuel_to_the_fire",
    word: "add fuel to the fire",
    usPronounce: "/æd fjuːəl tə ðə faɪr/",
    ukPronounce: "/æd fjuːəl tə ðə faɪə/",
    translation: "làm tình hình tệ hơn",
    remember: "Make it worse.",
  },
  {
    bookSlug: "oxford-idioms-and-phrasal-verbs-advanced",
    slug: "oxford-idioms-and-phrasal-verbs-advanced_hit_the_ground_running",
    word: "hit the ground running",
    usPronounce: "/hɪt ðə ɡraʊnd ˈrʌn.ɪŋ/",
    ukPronounce: "/hɪt ðə ɡraʊnd ˈrʌn.ɪŋ/",
    translation: "bắt đầu nhanh chóng",
    remember: "",
  },
  {
    bookSlug: "oxford-idioms-and-phrasal-verbs-advanced",
    slug: "oxford-idioms-and-phrasal-verbs-advanced_give_someone_the_benefit_of_the_doubt",
    word: "give someone the benefit of the doubt",
    usPronounce: "/ɡɪv ˈsʌm.wʌn ðə ˈben.ɪ.fɪt əv ðə daʊt/",
    ukPronounce: "/ɡɪv ˈsʌm.wʌn ðə ˈben.ɪ.fɪt əv ðə daʊt/",
    translation: "tin tưởng ai dù nghi ngờ",
    remember: "Trust first.",
  },
  {
    bookSlug: "oxford-idioms-and-phrasal-verbs-advanced",
    slug: "oxford-idioms-and-phrasal-verbs-advanced_keep_something_at_bay",
    word: "keep something at bay",
    usPronounce: "/kiːp ˈsʌm.θɪŋ æt beɪ/",
    ukPronounce: "/kiːp ˈsʌm.θɪŋ æt beɪ/",
    translation: "ngăn chặn điều gì",
    remember: "",
  },
  {
    bookSlug: "oxford-idioms-and-phrasal-verbs-advanced",
    slug: "oxford-idioms-and-phrasal-verbs-advanced_once_in_a_blue_moon",
    word: "once in a blue moon",
    usPronounce: "/wʌns ɪn ə bluː muːn/",
    ukPronounce: "/wʌns ɪn ə bluː muːn/",
    translation: "hiếm khi",
    remember: "Very rare.",
  },
  {
    bookSlug: "oxford-idioms-and-phrasal-verbs-advanced",
    slug: "oxford-idioms-and-phrasal-verbs-advanced_put_all_your_eggs_in_one_basket",
    word: "put all your eggs in one basket",
    usPronounce: "/pʊt ɔːl jʊr eɡz ɪn wʌn ˈbæs.kɪt/",
    ukPronounce: "/pʊt ɔːl jɔːr eɡz ɪn wʌn ˈbæs.kɪt/",
    translation: "đặt cược tất cả vào một chỗ",
    remember: "",
  },
  {
    bookSlug: "oxford-idioms-and-phrasal-verbs-advanced",
    slug: "oxford-idioms-and-phrasal-verbs-advanced_take_the_plunge",
    word: "take the plunge",
    usPronounce: "/teɪk ðə plʌndʒ/",
    ukPronounce: "/teɪk ðə plʌndʒ/",
    translation: "quyết định táo bạo",
    remember: "Dive in.",
  },
  {
    bookSlug: "oxford-idioms-and-phrasal-verbs-advanced",
    slug: "oxford-idioms-and-phrasal-verbs-advanced_bring_something_to_the_table",
    word: "bring something to the table",
    usPronounce: "/brɪŋ ˈsʌm.θɪŋ tə ðə ˈteɪ.bəl/",
    ukPronounce: "/brɪŋ ˈsʌm.θɪŋ tə ðə ˈteɪ.bəl/",
    translation: "đóng góp điều gì",
    remember: "",
  },
  {
    bookSlug: "oxford-idioms-and-phrasal-verbs-advanced",
    slug: "oxford-idioms-and-phrasal-verbs-advanced_call_it_a_day",
    word: "call it a day",
    usPronounce: "/kɔːl ɪt ə deɪ/",
    ukPronounce: "/kɔːl ɪt ə deɪ/",
    translation: "kết thúc công việc",
    remember: "Stop work.",
  },
  {
    bookSlug: "oxford-idioms-and-phrasal-verbs-advanced",
    slug: "oxford-idioms-and-phrasal-verbs-advanced_get_ahead_of_the_curve",
    word: "get ahead of the curve",
    usPronounce: "/ɡet əˈhed əv ðə kɝːv/",
    ukPronounce: "/ɡet əˈhed əv ðə kɜːv/",
    translation: "đi trước xu hướng",
    remember: "",
  },
  {
    bookSlug: "oxford-idioms-and-phrasal-verbs-advanced",
    slug: "oxford-idioms-and-phrasal-verbs-advanced_leave_no_stone_unturned",
    word: "leave no stone unturned",
    usPronounce: "/liːv noʊ stoʊn ʌnˈtɝːnd/",
    ukPronounce: "/liːv nəʊ stəʊn ʌnˈtɜːnd/",
    translation: "tìm mọi cách",
    remember: "Try everything.",
  },
  {
    bookSlug: "oxford-idioms-and-phrasal-verbs-advanced",
    slug: "oxford-idioms-and-phrasal-verbs-advanced_see_the_writing_on_the_wall",
    word: "see the writing on the wall",
    usPronounce: "/siː ðə ˈraɪ.tɪŋ ɑːn ðə wɔːl/",
    ukPronounce: "/siː ðə ˈraɪ.tɪŋ ɒn ðə wɔːl/",
    translation: "nhận ra dấu hiệu xấu",
    remember: "",
  },
  {
    bookSlug: "oxford-idioms-and-phrasal-verbs-advanced",
    slug: "oxford-idioms-and-phrasal-verbs-advanced_cut_corners",
    word: "cut corners",
    usPronounce: "/kʌt ˈkɔːr.nɚz/",
    ukPronounce: "/kʌt ˈkɔː.nəz/",
    translation: "làm ẩu",
    remember: "Save time poorly.",
  },
  {
    bookSlug: "oxford-idioms-and-phrasal-verbs-advanced",
    slug: "oxford-idioms-and-phrasal-verbs-advanced_get_the_hang_of",
    word: "get the hang of",
    usPronounce: "/ɡet ðə hæŋ əv/",
    ukPronounce: "/ɡet ðə hæŋ əv/",
    translation: "nắm bắt cách làm",
    remember: "",
  },
  {
    bookSlug: "oxford-idioms-and-phrasal-verbs-advanced",
    slug: "oxford-idioms-and-phrasal-verbs-advanced_keep_your_cards_close_to_your_chest",
    word: "keep your cards close to your chest",
    usPronounce: "/kiːp jʊr kɑːrdz kloʊs tə jʊr tʃest/",
    ukPronounce: "/kiːp jɔːr kɑːdz kləʊs tə jɔːr tʃest/",
    translation: "giữ kín kế hoạch",
    remember: "Stay secretive.",
  },
  {
    bookSlug: "oxford-idioms-and-phrasal-verbs-advanced",
    slug: "oxford-idioms-and-phrasal-verbs-advanced_take_something_in_your_stride",
    word: "take something in your stride",
    usPronounce: "/teɪk ˈsʌm.θɪŋ ɪn jʊr straɪd/",
    ukPronounce: "/teɪk ˈsʌm.θɪŋ ɪn jɔːr straɪd/",
    translation: "bình tĩnh xử lý",
    remember: "",
  },
  {
    bookSlug: "oxford-idioms-and-phrasal-verbs-advanced",
    slug: "oxford-idioms-and-phrasal-verbs-advanced_blow_off_steam",
    word: "blow off steam",
    usPronounce: "/bloʊ ɔːf stiːm/",
    ukPronounce: "/bləʊ ɒf stiːm/",
    translation: "giải tỏa căng thẳng",
    remember: "Relax.",
  },
  {
    bookSlug: "oxford-idioms-and-phrasal-verbs-advanced",
    slug: "oxford-idioms-and-phrasal-verbs-advanced_get_your_own_back",
    word: "get your own back",
    usPronounce: "/ɡet jʊr oʊn bæk/",
    ukPronounce: "/ɡet jɔːr əʊn bæk/",
    translation: "trả đũa",
    remember: "",
  },
  {
    bookSlug: "oxford-idioms-and-phrasal-verbs-advanced",
    slug: "oxford-idioms-and-phrasal-verbs-advanced_hold_your_horses",
    word: "hold your horses",
    usPronounce: "/hoʊld jʊr ˈhɔːr.sɪz/",
    ukPronounce: "/həʊld jɔːr ˈhɔː.sɪz/",
    translation: "chờ đã",
    remember: "Slow down.",
  },
  {
    bookSlug: "oxford-idioms-and-phrasal-verbs-advanced",
    slug: "oxford-idioms-and-phrasal-verbs-advanced_jump_ship",
    word: "jump ship",
    usPronounce: "/dʒʌmp ʃɪp/",
    ukPronounce: "/dʒʌmp ʃɪp/",
    translation: "bỏ việc",
    remember: "",
  },
  {
    bookSlug: "oxford-idioms-and-phrasal-verbs-advanced",
    slug: "oxford-idioms-and-phrasal-verbs-advanced_make_ends_meet",
    word: "make ends meet",
    usPronounce: "/meɪk endz miːt/",
    ukPronounce: "/meɪk endz miːt/",
    translation: "kiếm đủ sống",
    remember: "Balance budget.",
  },
  {
    bookSlug: "oxford-idioms-and-phrasal-verbs-advanced",
    slug: "oxford-idioms-and-phrasal-verbs-advanced_put_the_cart_before_the_horse",
    word: "put the cart before the horse",
    usPronounce: "/pʊt ðə kɑːrt bɪˈfɔːr ðə hɔːrs/",
    ukPronounce: "/pʊt ðə kɑːt bɪˈfɔːr ðə hɔːs/",
    translation: "làm ngược quy trình",
    remember: "",
  },
  {
    bookSlug: "oxford-idioms-and-phrasal-verbs-advanced",
    slug: "oxford-idioms-and-phrasal-verbs-advanced_stick_to_your_guns",
    word: "stick to your guns",
    usPronounce: "/stɪk tə jʊr ɡʌnz/",
    ukPronounce: "/stɪk tə jɔːr ɡʌnz/",
    translation: "kiên định lập trường",
    remember: "Stay firm.",
  },
  {
    bookSlug: "oxford-idioms-and-phrasal-verbs-advanced",
    slug: "oxford-idioms-and-phrasal-verbs-advanced_take_it_with_a_grain_of_salt",
    word: "take it with a grain of salt",
    usPronounce: "/teɪk ɪt wɪð ə ɡreɪn əv sɔːlt/",
    ukPronounce: "/teɪk ɪt wɪð ə ɡreɪn əv sɒlt/",
    translation: "nghi ngờ điều gì",
    remember: "",
  },
  {
    bookSlug: "oxford-idioms-and-phrasal-verbs-advanced",
    slug: "oxford-idioms-and-phrasal-verbs-advanced_weather_the_storm",
    word: "weather the storm",
    usPronounce: "/ˈweð.ɚ ðə stɔːrm/",
    ukPronounce: "/ˈweð.ə ðə stɔːm/",
    translation: "vượt qua khó khăn",
    remember: "Survive trouble.",
  },
  {
    bookSlug: "oxford-idioms-and-phrasal-verbs-advanced",
    slug: "oxford-idioms-and-phrasal-verbs-advanced_burn_bridges",
    word: "burn bridges",
    usPronounce: "/bɝːn ˈbrɪdʒ.ɪz/",
    ukPronounce: "/bɜːn ˈbrɪdʒ.ɪz/",
    translation: "cắt đứt quan hệ",
    remember: "",
  },
  {
    bookSlug: "oxford-idioms-and-phrasal-verbs-advanced",
    slug: "oxford-idioms-and-phrasal-verbs-advanced_get_to_the_bottom_of",
    word: "get to the bottom of",
    usPronounce: "/ɡet tə ðə ˈbɑː.təm əv/",
    ukPronounce: "/ɡet tə ðə ˈbɒt.əm əv/",
    translation: "tìm ra nguyên nhân",
    remember: "Solve mystery.",
  },
  {
    bookSlug: "oxford-idioms-and-phrasal-verbs-advanced",
    slug: "oxford-idioms-and-phrasal-verbs-advanced_have_a_bone_to_pick",
    word: "have a bone to pick",
    usPronounce: "/hæv ə boʊn tə pɪk/",
    ukPronounce: "/hæv ə bəʊn tə pɪk/",
    translation: "có vấn đề cần tranh luận",
    remember: "",
  },
  {
    bookSlug: "oxford-idioms-and-phrasal-verbs-advanced",
    slug: "oxford-idioms-and-phrasal-verbs-advanced_keep_an_eye_out",
    word: "keep an eye out",
    usPronounce: "/kiːp ən aɪ aʊt/",
    ukPronounce: "/kiːp ən aɪ aʊt/",
    translation: "để ý, cảnh giác",
    remember: "Watch carefully.",
  },
  {
    bookSlug: "oxford-idioms-and-phrasal-verbs-advanced",
    slug: "oxford-idioms-and-phrasal-verbs-advanced_play_it_by_ear",
    word: "play it by ear",
    usPronounce: "/pleɪ ɪt baɪ ɪr/",
    ukPronounce: "/pleɪ ɪt baɪ ɪə/",
    translation: "hành động tùy cơ ứng biến",
    remember: "",
  },
  {
    bookSlug: "oxford-idioms-and-phrasal-verbs-advanced",
    slug: "oxford-idioms-and-phrasal-verbs-advanced_rub_salt_in_the_wound",
    word: "rub salt in the wound",
    usPronounce: "/rʌb sɔːlt ɪn ðə wuːnd/",
    ukPronounce: "/rʌb sɒlt ɪn ðə wuːnd/",
    translation: "làm ai thêm đau khổ",
    remember: "Worsen pain.",
  },
  {
    bookSlug: "oxford-idioms-and-phrasal-verbs-advanced",
    slug: "oxford-idioms-and-phrasal-verbs-advanced_take_the_mickey",
    word: "take the mickey",
    usPronounce: "/teɪk ðə ˈmɪk.i/",
    ukPronounce: "/teɪk ðə ˈmɪk.i/",
    translation: "chế giễu",
    remember: "",
  },
];
